version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ilyrium-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ilyrium_pricing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ilyrium-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ilyrium-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ilyrium_pricing?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PRICE_MIN: 0.001
      PRICE_MAX: 0.01
      TOTAL_RPS: 10000
      ADMIN_KEY: ${ADMIN_KEY:-changeme}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/index.js
      "

volumes:
  postgres_data:
  redis_data:

