name: CI

on:
  pull_request:
    branches: [master, main, develop]
  push:
    branches: [master, main, develop]

jobs:
  build:
    name: Build & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.6.0'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npx prettier --check "src/**/*.{ts,js}" "migrations/**/*.ts"

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Build failed - dist directory not created"
            exit 1
          fi
          echo "✅ Build successful"
